### ISSUE TITLE
Snow Crystal AM

### ISSUE THREAD

**Issue by FurtakM** [FurtakM/SoS#16]
<p>Snow Crystal AM gra się nie kończy. Przekroczone 400, 500, 600 zebranych kryształów syberytu (na 400 wymaganych przy hardzie) i nic. Gra leci dalej. Wersja RUS działa poprawnie.</p><p>Zgłoszenie wygenerowane na stronie <a href='https://sand-of-siberia.pl'>sand-of-siberia.pl</a></p>

**Comment by Mieciu125** [comment]
ten błąd został już zgłoszony do serpenta i w najbliższym czasie zostanie naprawiony

**Comment by FurtakM** [comment]
Naprawione.
