### ISSUE TITLE
Wzywanie wsparcia - skirmish, brak ikonki

### ISSUE THREAD

**Issue by FurtakM** [FurtakM/SoS#17]
<p>Na patchu 216 lub 219 (nie pamiętam) nie działało wsparcie z magazynu w Potter Paradox.<br>Na 226 o tyle bez zmian, że tutaj grałem w Two Fronts - ta sama sytuacja. <br>Nie ma ikony, nie można wezwać. </p><p>Zgłoszenie wygenerowane na stronie <a href='https://sand-of-siberia.pl'>sand-of-siberia.pl</a></p>

**Comment by Mieciu125** [comment]
ten błąd został już zgłoszony do serpenta i w najbliższym czasie zostanie naprawiony

**Comment by FurtakM** [comment]
Naprawione.
