### ISSUE TITLE
Buged number of spawned troops in the start of the Ares mission 7

### ISSUE THREAD

**Issue by UltimateEvil** [FurtakM/SoS#266]
Depending on the units - and vehicles - you end with, you may end up only spawning 8 people and 9 vehicles with the last one empty. No people follow even more have left the last mission

See the relevant campaign saves with various endings, one spawns the proper amount of people and the others discard some
[CampaignSaves.zip](https://github.com/user-attachments/files/16937202/CampaignSaves.zip)

And a savefile which can trigger the mission end with whichever combination you want.
[X106 sechs.zip](https://github.com/user-attachments/files/16937209/X106.sechs.zip)

On another note, some of my apes are discarded as well, but I'd assume that is intentional.

On:
SOS ver Mod_Ver=1.6.2
OWAR ver 3.0.12.339

**Comment by FurtakM** [comment]
Fixed in https://github.com/FurtakM/SoS/pull/271/commits/b4940f41c03160440937d7470ecb3b60f5b79a16
