### ISSUE TITLE
[SGUI] Zmiana systemu sortowania biografii

### ISSUE THREAD

**Issue by Mietek125** [FurtakM/SoS#286]
Zmiana podstawowego sortowania biografii:

bioDefaultSort = {BIO_JMM, BIO_JOAN, BIO_BARN, BIO_BOBBY, BIO_CYRUS, BIO_LISA, BIO_KHAT, BIO_ANDY, BIO_FRANK, BIO_JEFF, BIO_LUCY, BIO_TIM, BIO_DENIS, BIO_ADAM, BIO_HARR, BIO_YAMO, BIO_HOUT, BIO_SIK, BIO_TRUM, BIO_GARY, BIO_POW, BIO_CATH, BIO_HUGH, BIO_ROTH, BIO_HEIKE, BIO_KAIA, BIO_OLAF, BIO_GIVI, BIO_MIKE, BIO_KAMI, BIO_AVIR, BIO_KRAY, BIO_SOPH, BIO_FARM, BIO_OMAR, BIO_IBRA, BIO_SHAR, BIO_KURT, BIO_ROLF, BIO_SHUL, BIO_JENN, BIO_LEMM, BIO_RONN, BIO_NIA, BIO_MIA, BIO_BASIM, BIO_GORKI, BIO_GNYE, BIO_BELK, BIO_JELE, BIO_KOVA, BIO_BELK2, BIO_KURIN, BIO_PLAT, BIO_POPO, BIO_SCHO, BIO_KUZM, BIO_GAYD. BIO_TIT, BIO_PETRO, BIO_DOLG, BIO_PETRS, BIO_GLEB, BIO_KARAM, BIO_YAKOT, BIO_SEVI, BIO_XAVI, BIO_YASH, BIO_KOZL, BIO_GOSS, BIO_GLAD, BIO_BYST, BIO_MICH, BIO_GENS,BIO_GALI, BIO_NICH, BIO_MARIA, BIO_JOACH, BIO_KARL, BIO_MARK, BIO_ANDRE, BIO_ERWIN, BIO_KOL, BIO_RICK}

**Comment by FurtakM** [comment]
![image](https://github.com/user-attachments/assets/8320887d-a150-463e-a629-a2096dab1286)

Zrealizowane.

Sortowanie ustawione po bioDefaultSort + nacja.
